### ISSUE TITLE
Error with the script

### ISSUE THREAD

**Issue by Nodam1** [Extraltodeus/depthmap2mask#10]
Clicking generate puts an error that says " ModuleNotFoundError: No module named 'repositories.midas' ", not sure what to do

**Comment by Bundo-san** [comment]
I'm running into the same issue. Looking at this [post](https://www.reddit.com/r/StableDiffusion/comments/yo87qz/comment/ive5k25/?utm_source=share&utm_medium=web2x&context=3) on reddit at the moment. Will report back if I have any luck.

**Comment by Nodam1** [comment]
> I'm running into the same issue. Looking at this [post](https://www.reddit.com/r/StableDiffusion/comments/yo87qz/comment/ive5k25/?utm_source=share&utm_medium=web2x&context=3) on reddit at the moment. Will report back if I have any luck.
> 
> Edit: ok ez fix, just clone the Midas repo to your repositories folder: git clone https://github.com/isl-org/MiDaS.git /path/to/stable-diffusion-webui/repositories/midas
> 
> Also thanks for making the depthmap2mask extension Extraltodeus!!

thank you!
