### ISSUE TITLE
(Feature request) Use existing depthmaps

### ISSUE THREAD

**Issue by pushstartvr** [Extraltodeus/depthmap2mask#17]
I would like to be able to use my own depthmap from a depth camera.  As you can see the depth maps have much more detail for th AI to work with and would create some amazing results.
Could we have the input image be our own 512 depth map? Or folder of depth maps.
Please and thank you.
![204748621-db256369-173c-40b5-b6b4-695d584fe069](https://user-images.githubusercontent.com/25425449/204924807-17e410c6-4643-410f-b031-6899a061d045.jpg)

**Comment by Extraltodeus** [comment]
You can already do that by using an image as a mask with the default webui stuff
![image](https://user-images.githubusercontent.com/15731540/205502683-73805b0e-249c-4135-9d6b-6633d6e0d8f7.png)

**Comment by pushstartvr** [comment]
Oh fantastic thank you so much

**Comment by pushstartvr** [comment]
Before I start a new request I just want to make sure I'm not missing
anything.
Is it possible to have a batch process for this?

What I'm trying to do is take a depth video of someone's face singing or
whatever, chop that into frames and apply those frames to the prompt.

Is this possible?

Cheers

**Comment by Extraltodeus** [comment]
I have not implemented batch processing for that script.

**Comment by pushstartvr** [comment]
Do you mind if I request it?
I haven't really interacted on github before so I don't wanna do the wrong
thing

**Comment by Extraltodeus** [comment]
sure go ahead but I might not do it before a while as I don't have a lot of free time lately. Some other dev passing by might notice it and make a pull request however so it can be beneficial.

**Comment by pushstartvr** [comment]
Awesome, thanks!
I'm only just starting to realise the potential if this.  Cheers
