### ISSUE TITLE
(Feature request) Integration with manual inpainting in Auto1111

### ISSUE THREAD

**Issue by samf1986** [Extraltodeus/depthmap2mask#18]
As far as I can tell, this extension currently ignores the manual masking in Auto1111. Taking the intersection of the two masks (multiply in PIL? Not sure what the easiest solution is) would allow users to apply the benefits of this extension to specific areas for touchup, and would allow users to take advantage of the higher local resolution when using "inpaint at full resolution" with a small masked area.

**Comment by Extraltodeus** [comment]
Since you can save the depthmap, you can also edit it and use it as a normal mask. I might add that shortcut at some point but I don't plan in doing it right now because I don't have much time for it. But indeed it would be practical in some cases.
