### ISSUE TITLE
Add "Show Depth Map" Option

### ISSUE THREAD

**Issue by TheEliteGeek** [Extraltodeus/depthmap2mask#2]
There should be a way to view the generated depth map within the web interface instead of having to save and view them from the img2img folder.

**Comment by lhucklen** [comment]
I agree. Can we make it similar to how this repository displays both results.

https://colab.research.google.com/github/backnotprop/Colab-Stable-Diffusion-2-Depth/blob/main/%5BColab_Gradio%5D_stable_diffusion_2_depth.ipynb

**Comment by AugmentedRealityCat** [comment]
This would be tremendously useful to adjust the parameters of this new feature I am requesting for better mask control:
https://github.com/Extraltodeus/depthmap2mask/issues/3

**Comment by Extraltodeus** [comment]
I mean you can already save the depth maps, they are just not shown in the webui.

**Comment by EricZeiberg** [comment]
It's very cumbersome to have to look at the file instead of it showing up in the UI, similar to [txt2mask](https://github.com/ThereforeGames/txt2mask)

**Comment by Extraltodeus** [comment]
all right

Can you test it?
Replace depth2image_depthmask.py by [this version](https://raw.githubusercontent.com/Extraltodeus/depthmap2mask/return_images_to_webui/scripts/depth2image_depthmask.py) before loading your UI

**Comment by AugmentedRealityCat** [comment]
For some reason I completely broke my Automatic1111 Webui install - I went up and down too many branches I suppose, and now there are conflicts.
I'll test that as soon as I fix my problems, and I'll also come back to you regarding my feature request and why it would be useful - that's what I was trying to achieve but IMG2IMG was broken and it's by trying to fix it that I f'ed everything else.

**Comment by Extraltodeus** [comment]
How I've been there so many times with so many dependancies. Good luck!

**Comment by AugmentedRealityCat** [comment]
> Can you test it? Replace depth2image_depthmask.py by [this version](https://raw.githubusercontent.com/Extraltodeus/depthmap2mask/return_images_to_webui/scripts/depth2image_depthmask.py) before loading your UI

**I tried it and it works !** Thank you so much, this makes everything so much easier to manage as you get visual feedback directly in the WebUI. 

A good tip: to speed things up while I'm adjusting the mask I simply set the denoising value to 0.00 this way the image is simply redrawn "as is", which takes a single step, and I only have to wait for the depthmap itself to be rendered.

**Comment by TheEliteGeek** [comment]
> all right
> 
> Can you test it? Replace depth2image_depthmask.py by [this version](https://raw.githubusercontent.com/Extraltodeus/depthmap2mask/return_images_to_webui/scripts/depth2image_depthmask.py) before loading your UI

This works! You rock!

**Comment by Extraltodeus** [comment]
Nice
