### ISSUE TITLE
Doubt about cpkt model

### ISSUE THREAD

**Issue by RafaRed** [Extraltodeus/depthmap2mask#4]
For 2.0, which cpkt model would be more ideal to use? I thought I should be using 512-depth-ema.ckpt, but I get the error that the midas_models folder doesn't exist.

**Comment by AugmentedRealityCat** [comment]
The 2.0 depth model is not supported by this extension. As far as I know it's not supported by Automatic1111 WebUI at all yet. The main reason seems to be that this new model also uses a new format with some extra data channels that were not used by previous models and which seems to be made to be connected with the new 2.0 inpainting model. 

For the moment, only the basic 2.0 models are supported and the 768 one seems to be easier to manager than the 512.

This depthmap2mask extension is made to work with any picture so it also works with images synthesized with the 2.0 models. 

T

**Comment by Extraltodeus** [comment]
Thank you @AugmentedRealityCat 

I'm closing this issue.
