### ISSUE TITLE
Using the dpt_large model kills my SD

### ISSUE THREAD

**Issue by BlastedRemnants** [Extraltodeus/depthmap2mask#9]
I've been playing with this script and I'm quite liking it so far, but after trying out the other models included I ran into a problem with the dpt_large model. I've been inpainting with the default small model and was having trouble getting the mask to fully cover my subject in a particular picture, so I thought to try the other models and I got better results with the v21 model and even better results with the dpt_large model, so that's good to know. However, after trying the dpt_large model once I immediately became unable to do any further generating without getting a memory error, I couldn't even do txt2img and had to close the console before being able to generate images again. I usually use --xformers but I decided to try --medvram to see if that would help with running the large model but the issue persists. If it helps any I'm running a 2070 Super with 8 gigs of vram on Win11, with up to date drivers for everything. I don't know if it'd be more preferred for me to paste a wall of text or attach a text file, but I'll share the console output both ways just to be sure. Output follows from here, thanks for your work!

[Memory Error - Console.txt](https://github.com/Extraltodeus/depthmap2mask/files/10112202/Memory.Error.-.Console.txt)

Traceback (most recent call last):
  File "C:\SDWebUI\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\SDWebUI\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\SDWebUI\modules\img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\SDWebUI\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "C:\SDWebUI\extensions\depthmap2mask\scripts\depth2image_depthmask.py", line 92, in run
    proc = process_images(p)
  File "C:\SDWebUI\modules\processing.py", line 430, in process_images
    res = process_images_inner(p)
  File "C:\SDWebUI\modules\processing.py", line 496, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\SDWebUI\modules\processing.py", line 841, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "C:\SDWebUI\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\SDWebUI\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "C:\SDWebUI\modules\lowvram.py", line 48, in first_stage_model_encode_wrap
    return first_stage_model_encode(x)
  File "C:\SDWebUI\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "C:\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SDWebUI\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 526, in forward
    h = self.down[i_level].block[i_block](hs[-1], temb)
  File "C:\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SDWebUI\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 138, in forward
    h = self.norm2(h)
  File "C:\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SDWebUI\venv\lib\site-packages\torch\nn\modules\normalization.py", line 272, in forward
    return F.group_norm(
  File "C:\SDWebUI\venv\lib\site-packages\torch\nn\functional.py", line 2516, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 8.00 GiB total capacity; 4.83 GiB already allocated; 0 bytes free; 6.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Redmail21** [comment]
Same issue here, in my case after 1 nice iteration it throws:

Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.23 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Also i have always been using the following arguments on the webui --opt-split-attention --precision full --no-half --medvram

**Comment by BlastedRemnants** [comment]
> using the following arguments on the webui --opt-split-attention --precision full --no-half --medvram

I just started trying --medvram yesterday, usually I run --xformers and --deepbooru but for testing purposes I did try with no args and exactly the same experience with the large model. One and done for now, but I definitely prefer it over the other two and I hope this gets sorted out so I/we can use it. It's all sorcery to me tho so I can't help directly.

**Comment by Extraltodeus** [comment]
It really just seems that you are lacking VRAM to run the large model.

**Comment by Redmail21** [comment]
> It really just seems that you are lacking VRAM to run the large model. Have you tried using --lowvram ?

Just tried that and interestingly for me it seems to work!, but now i just ask hope you don´t mind, Is there a way to enable -lowvram specifically for the img2img without having to restart the web ui everytime? Thanks btw

**Comment by BlastedRemnants** [comment]
> Have you tried using --lowvram ?

I haven't tried it yet, I was really hoping my gpu wasn't that lame already lol. Just trying --medvram felt like giving up and admitting it's too old and weak, if I try --lowvram next thing I'll be turning all my games down to medium graphics settings and truly giving up hahaha. But no, I guess I'll try it out just to see if it lets me use the large model more than once, if that fixes it tho then I'm with Redmail in hoping there might be some way to switch it on and off quickly in the future. Personally I'd rather use the midsize model than have to change any other settings, I'm still on the fence about keeping --medvram turned on and I'm a bit concerned about degrading my outputs with whatever sorcery the med and low ram settings do. But I'll be back soon to let you know if --lowvram fixes it for me, thanks! And sorry for rambling lol, I'm bad for that.

**Comment by Extraltodeus** [comment]
My GTX1070 is no match compared to a nice google colab. I would recommand you to use that instead.

**Comment by Redmail21** [comment]
Yeah i feel you guys, i guess this isn't the old days where  4+gb vram was top tier, the collab thing sounds neat, will look forward to it.
In any case i just duplicated the web-user bat with the -lowvram and set a desktop shortcut just for depth2mask, may come handy to BlastedRemmants if he like me wants push his gpu to the limits.

Thanks to both you, Godbless .

**Comment by BlastedRemnants** [comment]
> Have you tried using --lowvram ?

Well, I tried the --lowvram and got some interesting results so I did some more testing and now I'm down a rabbit-hole of trying different things and taking notes so I came back with the relevant bits for this issue. In any case the --lowvram did indeed let me use the large model repeatedly, but it was painfully slow and could only reliably do 1 image at a time, so I decided to go back to --medvram and compare times. When I tried it again with --medvram tho, this time it let me do batches of 2 over and over, and only got fussy when I got greedy and tried for 3. That got me a memory error and after that it whittled me back down to 1 at a time and then died out entirely shortly after. But while it was working it was doing 2 images in 38 seconds, while the --lowvram did 1 image in 1 minute. FYI these are 1152x768 images and I've got 8 gigs of ram in a 2070 Super, so it's a fairly heavy job for it but shouldn't be out of reach I wouldn't think. In any case all this testing got me curious and I'm going to do more comparisons but I think the best answer for me would be to just stick with the midsize model for now and wait for someone to tell GPT-3 to make us better xformers or whatever hahaha. Thanks for the help tho folks, I appreciate it and btw this script is epic and I'm having a ton of fun with the other one too, the Multi Subject Renderer. Keep it up please, thanks!

**Comment by Extraltodeus** [comment]
> 1 image at a time

You mean that you use the batch size all the time? This uses more ram or vram IIRC
